### ISSUE TITLE
Renderer interface

### ISSUE THREAD

**Issue by sbarisic** [Metapyziks/FacePuncher#20]
I was thinking about replacing the display class with a renderer interface and write CartConsole and Console renderers and let the user choose the default renderer in options or at startup so the master and cartconsole branches can be merged. It's harder to maintain 2 different branches.

**Comment by Metapyziks** [comment]
The deal with having separate branches is so that if someone wants just the original Console version they don't need all the SDL2 dlls, and so that other people can develop their own renderers on separate branches too with only their required dlls.

I'm not sure how it would be harder to develop, as long as you are only touching the rendering code you should be able to automatically merge from master to receive any changes there.

**Comment by sbarisic** [comment]
One could implement some kind of pak system like Quake 3 does and create different renderers as some kind of plugin, so if you want a different renderer you just download a pak file with the renderer binaries and the game can automatically load that renderer. A separate branch could be used for renderer development and the main branch for the loaders and stuff.

**Comment by Metapyziks** [comment]
Renderers can now be implemented with DLLs, and the one to use can be specified in [Data/interface.xml](https://github.com/Metapyziks/FacePuncher/blob/master/FacePuncher/Data/interface.xml).

Master branch now includes a [Win32Console](https://github.com/Metapyziks/FacePuncher/tree/master/FacePuncher.Win32Console) implementation and @cartman300 's [CartConsole](https://github.com/Metapyziks/FacePuncher/tree/master/FacePuncher.CartConsole).
