### ISSUE TITLE
Occasional bad initial visibility update

### ISSUE THREAD

**Issue by Metapyziks** [Metapyziks/FacePuncher#6]
I'm struggling to reliably reproduce this one, but it looks like the client occasionally gets some bad data during the first level status update after joining. The problem seems to come between reading a room rectangle and reading the tile count.

**Comment by Metapyziks** [comment]
I suppose this will be fixed during the communication rewrite anyway.

**Comment by Tamschi** [comment]
Yes, it was. (I think.)

I still need to do something to decouple the server and client. Currently the server is more or less lock-stepped because the TCP connection is blocking.

Since the level is mutable I'll have to make a snapshot and send that to the client without blocking. It already runs pretty fast though, if the updates were sparse there would be not much of a performance issue.

**Comment by Metapyziks** [comment]
Resolved.
